server {
  listen 443 ssl http2;
  server_name localhost;
  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy no-referrer always;
  add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
  add_header Content-Security-Policy "default-src 'self'; frame-ancestors 'none'; object-src 'none'; base-uri 'self'" always;
  client_max_body_size 1m;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Proto https;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  location /connect/token { proxy_no_cache 1; proxy_cache_bypass 1; proxy_pass http://identityserver:8080; }
  location / { proxy_pass http://identityserver:8080; }
}
